name: Run tests on push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Start server
        run: npm run start &

      - name: Wait for server to start
        run: npx wait-on http://localhost:3000

      - name: Run tests
        run: npx cypress run --e2e

      - name: Generate testing report
        run: npx mochawesome-merge "cypress/reports/*.json" > report.json && npx marge report.json --reportFilename "testing_report" --reportTitle "Cypress Report" --reportPageTitle "Cypress Report"

      - name: Upload testing report
        uses: actions/upload-artifact@v3
        with:
          name: testing_report
          path: mochawesome-report
