name: Run tests on push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Start server
        run: npm run start

      - name: Wait for server to start
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: npm run cypress run --e2e
