name: Run tests on push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Start server and run tests
        run: npm run start & npx wait-on http://localhost:3000 && npm run cypress run --e2e
